export const RouteBase = {
  Home: "/",
  Ielts: "/ielts",
  Login: "/login",
  IeltsListening: "/ielts/listening",
  IeltsReading: "/ielts/reading",
  IeltsWriting: "/ielts/writing",
  IeltsSpeaking: "/ielts/speaking",
  Pricing: "/pricing",
  ReviewExams: "/review-exams",
  Admin: "/admin",
  AdminLogin: "/admin/login",
  AdminDashboard: "/admin/dashboard",
  Listening: "/admin/listening",
  Speaking: "/admin/speaking",
  Writing: "/admin/writing",
  Reading: "/admin/reading",
  LoginEmail: "/login/email",
  SignUp: "/login/sign-up",
};
