export const RouteBase = {
  Home: "/",
  Ielts: "/ielts",
  Login: "/login",
  IeltsListening: "/ielts/listening",
  IeltsReading: "/ielts/reading",
  IeltsWriting: "/ielts/writing",
  IeltsSpeaking: "/ielts/speaking",
  Pricing: "/pricing",
  ReviewReading: "/ielts/review/reading",
  Admin: "/admin",
  AdminLogin: "/admin/login",
  AdminDashboard: "/admin/dashboard",
  Listening: "/admin/questionbank/listening",
  CreateListening: "/admin/questionbank/listening/create",
  Speaking: "/admin/questionbank/speaking",
  CreateSpeaking: "/admin/questionbank/speaking/create",
  Writing: "/admin/questionbank/writing",
  UpdateWriting: "/admin/questionbank/writing/:id",
  CreateWriting: "/admin/questionbank/writing/create",
  UpdateWritingWId: (id: string | number) => `/admin/questionbank/writing/${id}`,
  Reading: "/admin/questionbank/reading",
  CreateReading: "/admin/questionbank/reading/create",
  UpdateReading: "/admin/questionbank/reading/:id",
  UpdateReadingWId: (id: string | number) => `/admin/questionbank/reading/${id}`,
  LoginEmail: "/login/email",
  SignUp: "/login/sign-up",
};
