export const data = {
  statusCode: 200,
  message: "Success",
  success: true,
  data: {
    score: {
      total: 7.02,
      reading: null,
      writing: 7.02,
      speaking: null,
      listening: null,
      speaking_training_score: null,
    },
    speaking: [
      {
        questionId: "62ec0c33a0ec92c4ce39b871",
        studentAnswer: "abc",
        question: {
          _id: "62ec0c33a0ec92c4ce39b871",
          analysisType: "TREND",
          image: "uploads/2022/8/1/wr-t1-02outlined1bfe5e8f6fbc4843985015926a03c3c2-09560508082022285183.svg",
          text: "The line graph below shows the average height of women born between 1946 and 1996 in European countries. ",
          title: "Average height of women by year of birth",
          ideaSuggestion: null,
          modelAnswer:
            '<p><span style="color:#000000;">The line graph presents the average height data of women by year of birth in four countries in Europe between the years 1946 and 1996.&nbsp;</span></p><p>&nbsp;</p><p><span style="color:#000000;">Overall, women\'s average height grew steadily from 1946 to around 1970, after which point the growth trend either slowed down or was reversed.</span></p><p>&nbsp;</p><p><span style="color:#000000;">To begin with, France had the shortest average heights throughout the time period. The average height of French women in 1946 was just 161 centimeters. French women steadily grew in height from 1946 to around 1970. However, from this point onward France\'s average height began to level off at approximately 165 centimeters.</span></p><p>&nbsp;</p><p><span style="color:#000000;">While average heights in France experienced very slow growth after around 1970, heights in the Netherlands and Sweden began to shrink. While the heights of Dutch women decreased only slightly between roughly 1970 and 1996, Swedish women became shorter. Average heights of women in Sweden fell from around 167 centimeters in 1970 to under 166 centimeters in 1996.</span></p><p>&nbsp;</p><p><span style="color:#000000;">Latvia was the only country in which average heights continuously rose throughout the 50 year period. Despite the fact that women from this nation born in 1946 were only 164 centimeters tall on average, Latvian women had become the tallest group by 1996 with an average height of nearly 170 centimeters.</span></p><p>&nbsp;</p><p><span style="color:#000000;"><strong>[Word Count: 209]</strong></span></p><p><span style="color:#000000;"><strong>Estimated Band 8 or above</strong></span></p>',
          organization:
            '<ol style="list-style-type:upper-roman;"><li><span style="color:#000000;"><strong>Introduction: </strong>First, include an introductory sentence or paragraph explaining what the line graph shows. Paraphrase the description of the graph provided in the question.</span></li><li><span style="color:#000000;"><strong>Overview: </strong>Next, write a short overview of the general trend or trends shown in the graph. Do not go into details or cite numbers from the graph in this paragraph. Mention the overall increasing and/or decreasing trends and the highest and lowest points.</span></li><li><span style="color:#000000;"><strong>Body paragraphs:</strong> Consider writing two or three body paragraphs about any of the following:</span><ul style="list-style-type:circle;"><li><span style="color:#000000;">countries with shorter heights and countries with taller heights</span></li><li><span style="color:rgb(0,0,0);">general trends and specific details</span></li><li><span style="color:rgb(0,0,0);">heights which continued to grow and heights which leveled off</span></li></ul></li></ol>',
          tips: '<ul><li><span style="color:#000000;">Try to write around 170 - 200 words for this task. You will not get a higher score for a longer essay.&nbsp;</span></li><li><span style="color:#000000;">Remember to include a summary of the general trends in the graph. This overview paragraph is very important in Task 1.</span></li><li><span style="color:#000000;">Try not to simply list information and instead make comparisons.</span></li><li><span style="color:#000000;">Use transition words or connecting phrases such as \'overall\' and \'however\' to cohesively link the information.</span></li><li><span style="color:#000000;">You do not have to include a conclusion for this task.</span></li></ul>',
          usefulGrammarNVocab:
            '<p><span style="color:#000000;"><strong>Useful Grammar&nbsp;</strong></span></p><p><span style="color:#000000;">The following grammar structures can be useful for Trend questions:</span></p><ul><li><span style="color:#000000;">Past tense: The average height <i>increased</i>.&nbsp;</span></li><li><span style="color:#000000;">Comparison (high): Latvian women were <i>taller than </i>French women.</span></li><li><span style="color:#000000;">Comparison (low): Women were <i>shorter</i> in 1946 <i>than</i> in 1996.</span></li><li><span style="color:#000000;">Superlatives: The numbers increased <i>the most</i> in 1956.&nbsp;</span></li><li><span style="color:#000000;">Prepositions of time: <i>in, during, at, for, throughout</i></span></li></ul><p><span style="color:#000000;"><strong>Useful Vocabulary</strong></span></p><p><span style="color:#000000;">The following words and phrases can be useful for Trend questions:</span></p><ul><li><span style="color:#000000;">grow (verb) / shrink (verb)</span></li><li><span style="color:#000000;">rise (verb) / fall (verb)</span></li><li><span style="color:#000000;">level off (verb phrase)</span></li><li><span style="color:#000000;">dramatically (adverb)</span></li><li><span style="color:#000000;">steadily (adverb)</span></li></ul>',
          questionNumber: 1,
          displayNumber: "1",
        },
      },
      {
        questionId: "62ec0c33a0ec92c4ce39b872",
        studentAnswer: "nnn",
        question: {
          _id: "62ec0c33a0ec92c4ce39b872",
          analysisType: "NONE",
          image: null,
          text: "Societies produce more waste as they become more developed.\nWhy is this the case? What can be done about this problem?",
          title: "Societies produce more waste as they become more developed",
          ideaSuggestion:
            '<p><span style="color:#000000;"><strong>Possible Causes:</strong></span></p><ul><li><span style="color:#000000;">Recycling methods are not effective enough to keep up with the rate of consumption in developed countries.</span></li><li><span style="color:#000000;">People in developed societies are too reliant on single-use items like plastic utensils, straws, cups and bags.</span></li><li><span style="color:#000000;">Materials that items are made of, like types of plastic, take many years to decompose.&nbsp;</span></li></ul><p>&nbsp;</p><p><span style="color:#000000;"><strong>Possible Solutions:</strong></span></p><ul><li><span style="color:#000000;">Private companies should develop more ways to reuse discarded items.</span></li><li><span style="color:#000000;">Governments should regulate the amount of waste that private companies dispose of.</span></li><li><span style="color:#000000;">Scientists should focus on developing new biodegradable materials for use in manufacturing.</span></li></ul>',
          modelAnswer:
            '<p><span style="color:#000000;">When countries go through modernization, they begin to produce more and more waste, such as trash and uneaten food. These days, leaders in both public and private sectors are asking what can be done about this problem. However, we must first examine the causes in order to form effective solutions.</span></p><p>&nbsp;</p><p><span style="color:#000000;">The main cause of excess waste in developed countries is increased consumption. When a nation goes through the process of development, its citizens\' quality of life improves, but this also means that these citizens obtain greater financial autonomy and begin to buy more things. My home country of South Korea went through rapid economic growth in the 1970s. Although Koreans in the past lived more humble lives, now we are constantly encouraged to spend more on things like clothing, devices and food. As we buy more products, we throw away old ones, and mountains of trash and discarded items grow in landfills and in the streets.</span></p><p>&nbsp;</p><p><span style="color:#000000;">While the reasons why societies produce too much waste are relatively clear, the solutions are often debated. I believe that the most crucial step we must take to reduce the amount of trash is to reduce overconsumption. In other words, we need to live more minimalist lives. Despite the fact that most of us constantly buy new things, we rarely question whether or not we need these goods. For example, the fast-fashion industry produces enormous amounts of waste. People buy new clothing every season, and thus they periodically dispose of clothing that is still wearable. The fact is, however, that shoppers do not need to change their wardrobes so frequently. Instead, they could buy used or more durable clothing, which would result in less waste. Governments should also enforce better rules requiring private companies to be more responsible for the amount of waste that they produce.&nbsp;</span></p><p>&nbsp;</p><p><span style="color:#000000;">To sum up, the main cause of the waste problem in developed countries is the increased spending and consumption that results from modernization. Because of this, the main solution to this problem is to reduce overconsumption.</span></p><p>&nbsp;</p><p><span style="color:#000000;"><strong>[Word Count: 338]</strong></span></p><p><span style="color:#000000;"><strong>Estimated Band 8</strong></span></p>',
          organization:
            '<p><span style="color:#000000;">This is a two-part question, which means that you must respond to both questions included in the prompt. You can organize your essay into the following sections:&nbsp;</span></p><ol style="list-style-type:upper-roman;"><li><span style="color:#000000;"><strong>Introduction:</strong> First, write an introduction paragraph. You should include two pieces of information, or statements, in this paragraph. Start by paraphrasing the given question to provide context for your essay. Then, describe in one or two sentences what you will talk about in your essay. In this part, you can include what you think the main cause of the problem is and suggest one solution to the problem. Since the question does not mention \'causes\' and \'solutions\' in plural, you can just write about one cause and one solution.</span></li><li><span style="color:#000000;"><strong>Body paragraphs:</strong> Write one body paragraph about what you think is the main cause of the increasing waste problem and a second body paragraph about how to solve this problem. Alternatively, you can write one body paragraph about a cause and its corresponding solution, and a second body paragraph about another cause and solution.</span></li><li><span style="color:#000000;"><strong>Conclusion:</strong> Lastly, write a conclusion paragraph. You should write one to two sentences summarizing the main points raised in your body paragraphs.&nbsp;</span></li></ol>',
          tips: '<ul><li><span style="color:#000000;">Remember to address both the cause and the solution to the problem.</span></li><li><span style="color:#000000;">Make sure you link the cause and the solution in a meaningful way.</span></li><li><span style="color:#000000;">Give specific examples to support your ideas. Do not use overly general examples.&nbsp;</span></li><li><span style="color:#000000;">Try using structures with modal verbs such as <i>should</i>, <i>need to</i> or <i>must</i> when presenting your ideas, or conditional forms to express what <i>would</i> happen <i>if </i>certain policies <i>were implemented</i>.</span></li><li><span style="color:#000000;">Include a conclusion paragraph summarizing the argument(s) in your essay. You will receive a lower band score if you fail to include a conclusion.</span></li></ul>',
          usefulGrammarNVocab:
            '<p><span style="color:#000000;"><strong>Useful Grammar&nbsp;</strong></span></p><p><span style="color:#000000;">The following grammar structures can be useful for Trend questions:</span></p><ul><li><span style="color:#000000;">Past tense: The average height <i>increased</i>.&nbsp;</span></li><li><span style="color:#000000;">Comparison (high): Latvian women were <i>taller than </i>French women.</span></li><li><span style="color:#000000;">Comparison (low): Women were <i>shorter</i> in 1946 <i>than</i> in 1996.</span></li><li><span style="color:#000000;">Superlatives: The numbers increased <i>the most</i> in 1956.&nbsp;</span></li><li><span style="color:#000000;">Prepositions of time: <i>in, during, at, for, throughout</i></span></li></ul><p><span style="color:#000000;"><strong>Useful Vocabulary</strong></span></p><p><span style="color:#000000;">The following words and phrases can be useful for Trend questions:</span></p><ul><li><span style="color:#000000;">grow (verb) / shrink (verb)</span></li><li><span style="color:#000000;">rise (verb) / fall (verb)</span></li><li><span style="color:#000000;">level off (verb phrase)</span></li><li><span style="color:#000000;">dramatically (adverb)</span></li><li><span style="color:#000000;">steadily (adverb)</span></li></ul>',
          questionNumber: 2,
          displayNumber: "2",
        },
      },
    ],
  },
};
